"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%ptvvluox0-&j4r&#a2rtpu3m@%&j#9s(apml^okjpq6udcl$-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # apps
    'main',
    'users',
    # packages
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'corsheaders',
    'django_ckeditor_5'
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
        }
    },
    'PERSIST_AUTH': True
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

CORS_ALLOW_ALL_ORIGINS = True



CKEDITOR_5_CUSTOM_CSS = 'path/to/custom.css'

CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
CKEDITOR_5_UPLOAD_PATH = "ckeditor5/"

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'fontSize', 'fontColor', 'fontBackgroundColor', '|',
            'bold', 'italic', 'link', '|',
            'imageUpload', 'imageStyle:full', 'imageStyle:side', '|',
            'bulletedList', 'numberedList', 'todoList', '|',
            'codeBlock', 'emoji', '|',
            'undo', 'redo'
        ],
        'language': 'en',
        'image': {
            'toolbar': [
                'imageTextAlternative',
                'imageStyle:full',
                'imageStyle:side'
            ],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignCenter',
                'alignRight'
            ]
        },
        'fontSize': {
            'options': [8, 10, 12, 14, 16, 18, 24, 32, 48],
            'supportAllValues': True
        },
        'fontColor': {
            'colors': [
                {'color': '#000000', 'label': 'Black'},
                {'color': '#FF0000', 'label': 'Red'},
                {'color': '#00FF00', 'label': 'Green'},
                {'color': '#0000FF', 'label': 'Blue'},
                {'color': '#FFFF00', 'label': 'Yellow'},
                {'color': '#FFA500', 'label': 'Orange'},
                {'color': '#800080', 'label': 'Purple'}
            ],
            'columns': 5
        },
        'fontBackgroundColor': {
            'colors': [
                {'color': '#FFFFFF', 'label': 'White'},
                {'color': '#000000', 'label': 'Black'},
                {'color': '#FFEB3B', 'label': 'Light Yellow'},
                {'color': '#B3E5FC', 'label': 'Light Blue'},
                {'color': '#C8E6C9', 'label': 'Light Green'}
            ],
            'columns': 5
        }
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
if DEBUG:
    STATICFILES_DIRS = [BASE_DIR / 'static']
else:
    STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'

JAZZMIN_SETTINGS = {
    "site_title": "ProArabic Admin",
    "site_header": "ProArabic Admin Panel",
    "site_brand": "ProArabic",
    "welcome_sign": "ProArabic boshqaruv paneliga xush kelibsiz",
    "copyright": "ProArabic",
    "show_ui_builder": True,  # UI Builder menyuni yoqadi (dizayn o'zgartirish menyusi)

    # Logo va favicon
    "site_logo": "pro.jpg",     # STATIC papkaga qo'yasiz
    "site_logo_classes": "img-circle",
    "site_icon": "pro.jpg",

    # Admin Panel Theme
    "theme": "darkly",  # Cosmo, Flatly, Darkly, Solar, Morph, Quartz, Lux, Pulse

    # Top Menu
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Site", "url": "https://proarabic.uz", "new_tab": True},
    ],

    # Sidebar sozlamalari
    "navigation_expanded": True,
}

# 🔽 DIZAYN UCHUN MAXIMAL DARADA O'ZGARTIRISH
JAZZMIN_UI_TWEAKS = {
    "theme": "light",                   # yoki: light, flatly, cosmo, litera...
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,

    # Ranglar
    "accent": "primary",                 # primary, warning, danger, info, success
    "navbar": "navbar-dark bg-primary",  # fon rang
    "no_navbar_border": False,
    "navbar_fixed": True,

    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",   # yoki sidebar-light-success
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,

    # Forma dizayni
    "forms": {
        "input_size": "input-lg",        # input-sm, input-md, input-lg
        "form_horizontal": False,
        "label_class": "",
        "field_class": "",
    },

    # Tugmalar
    "button_classes": {
        "default": "btn btn-primary",
        "primary": "btn btn-primary",
        "success": "btn btn-success",
        "info": "btn btn-info",
        "warning": "btn btn-warning",
        "danger": "btn btn-danger",
    },
}
