# Generated by Django 6.0 on 2025-12-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='title',
            new_name='name',
        ),
    ]
